services:
  - type: web
    name: figmaguard-backend
    env: python
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "python server.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
